// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: distributor-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoCodec int32

const (
	VideoCodec_Libx264 VideoCodec = 0
	VideoCodec_Libx265 VideoCodec = 1
	VideoCodec_Vpx     VideoCodec = 2
	VideoCodec_Vp8     VideoCodec = 3
	VideoCodec_Vp9     VideoCodec = 4
)

// Enum value maps for VideoCodec.
var (
	VideoCodec_name = map[int32]string{
		0: "Libx264",
		1: "Libx265",
		2: "Vpx",
		3: "Vp8",
		4: "Vp9",
	}
	VideoCodec_value = map[string]int32{
		"Libx264": 0,
		"Libx265": 1,
		"Vpx":     2,
		"Vp8":     3,
		"Vp9":     4,
	}
)

func (x VideoCodec) Enum() *VideoCodec {
	p := new(VideoCodec)
	*p = x
	return p
}

func (x VideoCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_distributor_service_proto_enumTypes[0].Descriptor()
}

func (VideoCodec) Type() protoreflect.EnumType {
	return &file_distributor_service_proto_enumTypes[0]
}

func (x VideoCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoCodec.Descriptor instead.
func (VideoCodec) EnumDescriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{0}
}

type AudioCodec int32

const (
	AudioCodec_Aac  AudioCodec = 0
	AudioCodec_Ac3  AudioCodec = 1
	AudioCodec_Opus AudioCodec = 2
)

// Enum value maps for AudioCodec.
var (
	AudioCodec_name = map[int32]string{
		0: "Aac",
		1: "Ac3",
		2: "Opus",
	}
	AudioCodec_value = map[string]int32{
		"Aac":  0,
		"Ac3":  1,
		"Opus": 2,
	}
)

func (x AudioCodec) Enum() *AudioCodec {
	p := new(AudioCodec)
	*p = x
	return p
}

func (x AudioCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_distributor_service_proto_enumTypes[1].Descriptor()
}

func (AudioCodec) Type() protoreflect.EnumType {
	return &file_distributor_service_proto_enumTypes[1]
}

func (x AudioCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioCodec.Descriptor instead.
func (AudioCodec) EnumDescriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{1}
}

type MediaFileType int32

const (
	MediaFileType_Mp4  MediaFileType = 0
	MediaFileType_Mkv  MediaFileType = 1
	MediaFileType_Webm MediaFileType = 2
)

// Enum value maps for MediaFileType.
var (
	MediaFileType_name = map[int32]string{
		0: "Mp4",
		1: "Mkv",
		2: "Webm",
	}
	MediaFileType_value = map[string]int32{
		"Mp4":  0,
		"Mkv":  1,
		"Webm": 2,
	}
)

func (x MediaFileType) Enum() *MediaFileType {
	p := new(MediaFileType)
	*p = x
	return p
}

func (x MediaFileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaFileType) Descriptor() protoreflect.EnumDescriptor {
	return file_distributor_service_proto_enumTypes[2].Descriptor()
}

func (MediaFileType) Type() protoreflect.EnumType {
	return &file_distributor_service_proto_enumTypes[2]
}

func (x MediaFileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaFileType.Descriptor instead.
func (MediaFileType) EnumDescriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{2}
}

type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

// Enum value maps for UploadStatusCode.
var (
	UploadStatusCode_name = map[int32]string{
		0: "Unknown",
		1: "Ok",
		2: "Failed",
	}
	UploadStatusCode_value = map[string]int32{
		"Unknown": 0,
		"Ok":      1,
		"Failed":  2,
	}
)

func (x UploadStatusCode) Enum() *UploadStatusCode {
	p := new(UploadStatusCode)
	*p = x
	return p
}

func (x UploadStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_distributor_service_proto_enumTypes[3].Descriptor()
}

func (UploadStatusCode) Type() protoreflect.EnumType {
	return &file_distributor_service_proto_enumTypes[3]
}

func (x UploadStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatusCode.Descriptor instead.
func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{3}
}

type ProgressState int32

const (
	ProgressState_Distributing ProgressState = 0
	ProgressState_Transcoding  ProgressState = 1
)

// Enum value maps for ProgressState.
var (
	ProgressState_name = map[int32]string{
		0: "Distributing",
		1: "Transcoding",
	}
	ProgressState_value = map[string]int32{
		"Distributing": 0,
		"Transcoding":  1,
	}
)

func (x ProgressState) Enum() *ProgressState {
	p := new(ProgressState)
	*p = x
	return p
}

func (x ProgressState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressState) Descriptor() protoreflect.EnumDescriptor {
	return file_distributor_service_proto_enumTypes[4].Descriptor()
}

func (ProgressState) Type() protoreflect.EnumType {
	return &file_distributor_service_proto_enumTypes[4]
}

func (x ProgressState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressState.Descriptor instead.
func (ProgressState) EnumDescriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{4}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{0}
}

type ClusterClientOffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxConcurrentJobs int64 `protobuf:"varint,1,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
}

func (x *ClusterClientOffer) Reset() {
	*x = ClusterClientOffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterClientOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterClientOffer) ProtoMessage() {}

func (x *ClusterClientOffer) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterClientOffer.ProtoReflect.Descriptor instead.
func (*ClusterClientOffer) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterClientOffer) GetMaxConcurrentJobs() int64 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

type VideoSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codec VideoCodec `protobuf:"varint,1,opt,name=codec,proto3,enum=VideoCodec" json:"codec,omitempty"`
}

func (x *VideoSettings) Reset() {
	*x = VideoSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSettings) ProtoMessage() {}

func (x *VideoSettings) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSettings.ProtoReflect.Descriptor instead.
func (*VideoSettings) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{2}
}

func (x *VideoSettings) GetCodec() VideoCodec {
	if x != nil {
		return x.Codec
	}
	return VideoCodec_Libx264
}

type AudioSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codec AudioCodec `protobuf:"varint,2,opt,name=codec,proto3,enum=AudioCodec" json:"codec,omitempty"`
}

func (x *AudioSettings) Reset() {
	*x = AudioSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSettings) ProtoMessage() {}

func (x *AudioSettings) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSettings.ProtoReflect.Descriptor instead.
func (*AudioSettings) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{3}
}

func (x *AudioSettings) GetCodec() AudioCodec {
	if x != nil {
		return x.Codec
	}
	return AudioCodec_Aac
}

type TranscodingSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoSettings *VideoSettings `protobuf:"bytes,1,opt,name=video_settings,json=videoSettings,proto3" json:"video_settings,omitempty"`
	AudioSettings *AudioSettings `protobuf:"bytes,2,opt,name=audio_settings,json=audioSettings,proto3" json:"audio_settings,omitempty"`
	MediaFileType MediaFileType  `protobuf:"varint,3,opt,name=media_file_type,json=mediaFileType,proto3,enum=MediaFileType" json:"media_file_type,omitempty"`
}

func (x *TranscodingSettings) Reset() {
	*x = TranscodingSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodingSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodingSettings) ProtoMessage() {}

func (x *TranscodingSettings) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodingSettings.ProtoReflect.Descriptor instead.
func (*TranscodingSettings) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{4}
}

func (x *TranscodingSettings) GetVideoSettings() *VideoSettings {
	if x != nil {
		return x.VideoSettings
	}
	return nil
}

func (x *TranscodingSettings) GetAudioSettings() *AudioSettings {
	if x != nil {
		return x.AudioSettings
	}
	return nil
}

func (x *TranscodingSettings) GetMediaFileType() MediaFileType {
	if x != nil {
		return x.MediaFileType
	}
	return MediaFileType_Mp4
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReferenceNumber     int64                `protobuf:"varint,2,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	TranscodingSettings *TranscodingSettings `protobuf:"bytes,3,opt,name=transcoding_settings,json=transcodingSettings,proto3" json:"transcoding_settings,omitempty"`
	InputFileName       string               `protobuf:"bytes,4,opt,name=input_file_name,json=inputFileName,proto3" json:"input_file_name,omitempty"`
	InputFileData       []byte               `protobuf:"bytes,5,opt,name=input_file_data,json=inputFileData,proto3" json:"input_file_data,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{5}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetReferenceNumber() int64 {
	if x != nil {
		return x.ReferenceNumber
	}
	return 0
}

func (x *Job) GetTranscodingSettings() *TranscodingSettings {
	if x != nil {
		return x.TranscodingSettings
	}
	return nil
}

func (x *Job) GetInputFileName() string {
	if x != nil {
		return x.InputFileName
	}
	return ""
}

func (x *Job) GetInputFileData() []byte {
	if x != nil {
		return x.InputFileData
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId              string           `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobReferenceNumber int64            `protobuf:"varint,2,opt,name=job_reference_number,json=jobReferenceNumber,proto3" json:"job_reference_number,omitempty"`
	StatusCode         UploadStatusCode `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3,enum=UploadStatusCode" json:"status_code,omitempty"`
	OutputFileData     []byte           `protobuf:"bytes,4,opt,name=output_file_data,json=outputFileData,proto3" json:"output_file_data,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{6}
}

func (x *Result) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Result) GetJobReferenceNumber() int64 {
	if x != nil {
		return x.JobReferenceNumber
	}
	return 0
}

func (x *Result) GetStatusCode() UploadStatusCode {
	if x != nil {
		return x.StatusCode
	}
	return UploadStatusCode_Unknown
}

func (x *Result) GetOutputFileData() []byte {
	if x != nil {
		return x.OutputFileData
	}
	return nil
}

type TranscodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputFileName       string               `protobuf:"bytes,1,opt,name=input_file_name,json=inputFileName,proto3" json:"input_file_name,omitempty"`
	InputFileData       []byte               `protobuf:"bytes,2,opt,name=input_file_data,json=inputFileData,proto3" json:"input_file_data,omitempty"`
	TranscodingSettings *TranscodingSettings `protobuf:"bytes,3,opt,name=transcoding_settings,json=transcodingSettings,proto3" json:"transcoding_settings,omitempty"`
}

func (x *TranscodeRequest) Reset() {
	*x = TranscodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeRequest) ProtoMessage() {}

func (x *TranscodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeRequest.ProtoReflect.Descriptor instead.
func (*TranscodeRequest) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{7}
}

func (x *TranscodeRequest) GetInputFileName() string {
	if x != nil {
		return x.InputFileName
	}
	return ""
}

func (x *TranscodeRequest) GetInputFileData() []byte {
	if x != nil {
		return x.InputFileData
	}
	return nil
}

func (x *TranscodeRequest) GetTranscodingSettings() *TranscodingSettings {
	if x != nil {
		return x.TranscodingSettings
	}
	return nil
}

type TranscodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid       string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	StatusCode UploadStatusCode `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3,enum=UploadStatusCode" json:"status_code,omitempty"`
}

func (x *TranscodeResponse) Reset() {
	*x = TranscodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeResponse) ProtoMessage() {}

func (x *TranscodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeResponse.ProtoReflect.Descriptor instead.
func (*TranscodeResponse) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{8}
}

func (x *TranscodeResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TranscodeResponse) GetStatusCode() UploadStatusCode {
	if x != nil {
		return x.StatusCode
	}
	return UploadStatusCode_Unknown
}

type ProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProgressRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    ProgressState `protobuf:"varint,1,opt,name=state,proto3,enum=ProgressState" json:"state,omitempty"`
	Progress float32       `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{10}
}

func (x *ProgressResponse) GetState() ProgressState {
	if x != nil {
		return x.State
	}
	return ProgressState_Distributing
}

func (x *ProgressResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type RetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RetrieveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputFileName string `protobuf:"bytes,1,opt,name=output_file_name,json=outputFileName,proto3" json:"output_file_name,omitempty"`
	OutputFileData []byte `protobuf:"bytes,2,opt,name=output_file_data,json=outputFileData,proto3" json:"output_file_data,omitempty"`
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributor_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributor_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_distributor_service_proto_rawDescGZIP(), []int{12}
}

func (x *RetrieveResponse) GetOutputFileName() string {
	if x != nil {
		return x.OutputFileName
	}
	return ""
}

func (x *RetrieveResponse) GetOutputFileData() []byte {
	if x != nil {
		return x.OutputFileData
	}
	return nil
}

var File_distributor_service_proto protoreflect.FileDescriptor

var file_distributor_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x61,
	0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6a, 0x6f, 0x62,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6e, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x22, 0x32, 0x0a, 0x0d, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x22, 0x32,
	0x0a, 0x0d, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x21, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b,
	0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x52, 0x05, 0x63, 0x6f, 0x64,
	0x65, 0x63, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x0e, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x0d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x35, 0x0a, 0x0e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x0d, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x36, 0x0a, 0x0f, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x22, 0xd9, 0x01, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x26, 0x0a, 0x0f,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0xaf, 0x01, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x30,
	0x0a, 0x14, 0x6a, 0x6f, 0x62, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6a, 0x6f,
	0x62, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x32, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0xab,
	0x01, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x47, 0x0a, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x5b, 0x0a, 0x11,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x22, 0x54, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x66, 0x0a,
	0x10, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x41, 0x0a, 0x0a, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x63, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x69, 0x62, 0x78, 0x32, 0x36, 0x34, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x69, 0x62, 0x78, 0x32, 0x36, 0x35, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x56, 0x70, 0x78, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x56, 0x70, 0x38, 0x10, 0x03, 0x12,
	0x07, 0x0a, 0x03, 0x56, 0x70, 0x39, 0x10, 0x04, 0x2a, 0x28, 0x0a, 0x0a, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x61, 0x63, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x63, 0x33, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x70, 0x75, 0x73,
	0x10, 0x02, 0x2a, 0x2b, 0x0a, 0x0d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x70, 0x34, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x4d, 0x6b, 0x76, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x65, 0x62, 0x6d, 0x10, 0x02, 0x2a,
	0x33, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x10, 0x02, 0x2a, 0x32, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x32, 0x65, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c,
	0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x13, 0x2e,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x1a, 0x04, 0x2e, 0x4a, 0x6f, 0x62, 0x22, 0x00, 0x30, 0x01, 0x12, 0x21, 0x0a, 0x0c,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x07, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32,
	0xaa, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34,
	0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x10, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_distributor_service_proto_rawDescOnce sync.Once
	file_distributor_service_proto_rawDescData = file_distributor_service_proto_rawDesc
)

func file_distributor_service_proto_rawDescGZIP() []byte {
	file_distributor_service_proto_rawDescOnce.Do(func() {
		file_distributor_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_distributor_service_proto_rawDescData)
	})
	return file_distributor_service_proto_rawDescData
}

var file_distributor_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_distributor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_distributor_service_proto_goTypes = []interface{}{
	(VideoCodec)(0),             // 0: VideoCodec
	(AudioCodec)(0),             // 1: AudioCodec
	(MediaFileType)(0),          // 2: MediaFileType
	(UploadStatusCode)(0),       // 3: UploadStatusCode
	(ProgressState)(0),          // 4: ProgressState
	(*Empty)(nil),               // 5: Empty
	(*ClusterClientOffer)(nil),  // 6: ClusterClientOffer
	(*VideoSettings)(nil),       // 7: VideoSettings
	(*AudioSettings)(nil),       // 8: AudioSettings
	(*TranscodingSettings)(nil), // 9: TranscodingSettings
	(*Job)(nil),                 // 10: Job
	(*Result)(nil),              // 11: Result
	(*TranscodeRequest)(nil),    // 12: TranscodeRequest
	(*TranscodeResponse)(nil),   // 13: TranscodeResponse
	(*ProgressRequest)(nil),     // 14: ProgressRequest
	(*ProgressResponse)(nil),    // 15: ProgressResponse
	(*RetrieveRequest)(nil),     // 16: RetrieveRequest
	(*RetrieveResponse)(nil),    // 17: RetrieveResponse
}
var file_distributor_service_proto_depIdxs = []int32{
	0,  // 0: VideoSettings.codec:type_name -> VideoCodec
	1,  // 1: AudioSettings.codec:type_name -> AudioCodec
	7,  // 2: TranscodingSettings.video_settings:type_name -> VideoSettings
	8,  // 3: TranscodingSettings.audio_settings:type_name -> AudioSettings
	2,  // 4: TranscodingSettings.media_file_type:type_name -> MediaFileType
	9,  // 5: Job.transcoding_settings:type_name -> TranscodingSettings
	3,  // 6: Result.status_code:type_name -> UploadStatusCode
	9,  // 7: TranscodeRequest.transcoding_settings:type_name -> TranscodingSettings
	3,  // 8: TranscodeResponse.status_code:type_name -> UploadStatusCode
	4,  // 9: ProgressResponse.state:type_name -> ProgressState
	6,  // 10: DistributorService.JoinCluster:input_type -> ClusterClientOffer
	11, // 11: DistributorService.UploadResult:input_type -> Result
	12, // 12: CliService.Transcode:input_type -> TranscodeRequest
	14, // 13: CliService.Progress:input_type -> ProgressRequest
	16, // 14: CliService.Retrieve:input_type -> RetrieveRequest
	10, // 15: DistributorService.JoinCluster:output_type -> Job
	5,  // 16: DistributorService.UploadResult:output_type -> Empty
	13, // 17: CliService.Transcode:output_type -> TranscodeResponse
	15, // 18: CliService.Progress:output_type -> ProgressResponse
	17, // 19: CliService.Retrieve:output_type -> RetrieveResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_distributor_service_proto_init() }
func file_distributor_service_proto_init() {
	if File_distributor_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_distributor_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterClientOffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodingSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributor_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_distributor_service_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_distributor_service_proto_goTypes,
		DependencyIndexes: file_distributor_service_proto_depIdxs,
		EnumInfos:         file_distributor_service_proto_enumTypes,
		MessageInfos:      file_distributor_service_proto_msgTypes,
	}.Build()
	File_distributor_service_proto = out.File
	file_distributor_service_proto_rawDesc = nil
	file_distributor_service_proto_goTypes = nil
	file_distributor_service_proto_depIdxs = nil
}
